-- CreateTable
CREATE TABLE "patients" (
    "mrn" TEXT NOT NULL PRIMARY KEY,
    "firstname" TEXT NOT NULL,
    "lastname" TEXT NOT NULL,
    "sex" TEXT NOT NULL,
    "dob" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "generalPractitionerName" TEXT,
    "primaryCardiologistName" TEXT,
    "structuralCardiologistName" TEXT,
    "height" INTEGER,
    "weight" INTEGER,
    "diagnosis" TEXT,
    "summary" TEXT,
    "clinicalHistory" TEXT,
    "pastHistory" TEXT,
    "medications" TEXT,
    "allergies" TEXT,
    "NYHA" INTEGER,
    "angina" BOOLEAN,
    "syncope" BOOLEAN,
    "heartFailureAdmission" BOOLEAN,
    "orthopnea" BOOLEAN,
    "PND" BOOLEAN,
    "heartFailure" BOOLEAN,
    "heartFailureDetails" TEXT,
    "IHD" BOOLEAN,
    "IHDDetails" TEXT,
    "previousMI" BOOLEAN,
    "previousPCI" BOOLEAN,
    "PCIDetails" TEXT,
    "previousCardiacSurgery" TEXT,
    "cardiacSurgeryDetails" TEXT,
    "previousCABG" BOOLEAN,
    "previousSAVR" BOOLEAN,
    "previousStructuralIntervention" BOOLEAN,
    "structuralInterventionDetails" TEXT,
    "previousTAVI" BOOLEAN,
    "previousBAV" BOOLEAN,
    "AF" BOOLEAN,
    "AFDetails" TEXT,
    "implantableCardiacDevice" BOOLEAN,
    "implantableCardiacDeviceDetails" TEXT,
    "previousStrokeOrTIA" BOOLEAN,
    "strokeAndTIADetails" TEXT,
    "carotidArteryDisease" BOOLEAN,
    "carotidArteryDiseaseDetails" TEXT,
    "peripheralArteryDisease" BOOLEAN,
    "peripheralArteryDiseaseDetails" TEXT,
    "smoker" TEXT,
    "lungDisease" BOOLEAN,
    "lungDiseaseDetails" TEXT,
    "hypertension" BOOLEAN,
    "diabetes" TEXT,
    "chronicKidneyDisease" BOOLEAN,
    "dialysis" TEXT,
    "porcelainAorta" BOOLEAN,
    "hostileChest" BOOLEAN,
    "chestRadiotherapy" BOOLEAN,
    "steroids" BOOLEAN
);

-- CreateTable
CREATE TABLE "conferences" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "date" DATETIME,
    "diagnosis" TEXT NOT NULL,
    "proposal" TEXT NOT NULL,
    "patientId" TEXT NOT NULL,
    CONSTRAINT "conferences_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "patients" ("mrn") ON DELETE RESTRICT ON UPDATE CASCADE
);
